wallpaper {
    monitor = eDP-1
    path = /home/Pidguit/Pictures/Wallpapers/Batman Annual 2 by Lee Works.png
    #path = /home/Pidguit/Pictures/Wallpapers/KPDH Second Meeting by Sony Animations.png
    #path = /home/Pidguit/Pictures/Wallpapers/BTSV Teaser Art.jpg
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/Pidguit/Pictures/Wallpapers/Batman Annual 2 by Lee Works.png
    #path = /home/Pidguit/Pictures/Wallpapers/KPDH Second Meeting by Sony Animations.png
    #path = /home/Pidguit/Pictures/Wallpapers/BTSV Teaser Art.jpg
}

splash = false
ipc = true
