# Minimal Zsh config

# Prompt
PROMPT=' %F{13}%n%F{69} > %F{15}%~ %F{10}$%f '

# Enable command auto-correction
unsetopt correct

# Enable command history
HISTFILE=~/.zsh_history
HISTSIZE=5000
SAVEHIST=5000
HISTDUP=erase

# Share history across terminals
setopt share_history 
setopt hist_ignore_all_dups
setopt auto_cd
# Autocompletion
autoload -Uz compinit
compinit

# Enable color output for ls and grep
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias neofetch='fastfetch'
alias refresh='source ~/.zshrc'
alias zshedit='nvim ~/.config/zsh/zshrc'
alias update='sudo pacman -Syu;flatpak update'

# Changes the correct syntax color, plugin sourced below
typeset -A ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[command]='fg=15'
ZSH_HIGHLIGHT_STYLES[builtin]='fg=15'
ZSH_HIGHLIGHT_STYLES[alias]='fg=15'

# Turning on Plugins
source ~/.config/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source ~/.config/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

bindkey ^J forward-char # This just changes ctrl+j to right arrow, which is useful when used with autocorrect. Default bind is enter
