# Minimal Zsh config

# Prompt
PROMPT=' %F{13}%n%F{69} > %F{15}%~ %F{10}$%f '

# Loads all custom binds
source ~/.config/zsh/binds.zsh

# Enable command auto-correction
unsetopt correct

# Sets up command history 
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
HISTDUP=erase
setopt share_history 
setopt hist_ignore_all_dups

# Sets up cd without having to type in cd
setopt auto_cd

# Autocompletion
autoload -Uz compinit
compinit

# Loads all my custom aliases
source ~/.config/zsh/alias.zsh

# Changes the correct syntax color, plugin sourced below
typeset -A ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[command]='fg=15'
ZSH_HIGHLIGHT_STYLES[builtin]='fg=15'
ZSH_HIGHLIGHT_STYLES[alias]='fg=15'

# Turning on Plugins
source ~/.config/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source ~/.config/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Set up fzf key bindings and fuzzy completion
# source <(fzf --zsh)
# source ~/.config/zsh/plugins/fzf

#autoload -Uz compinit
#compinit
#source <(fzf --zsh)
#o
alias portopenuxplay='sudo ufw allow 5353/udp; sudo ufw allow 7100/tcp; sudo ufw allow 7000/tcp; sudo ufw allow 7001/tcp; sudo ufw allow 7011/udp; sudo ufw allow 6001/udp; sudo ufw allow 6000/udp; sudo ufw allow proto udp to 224.0.0.251 port 5353'
alias portcloseuxplay='sudo ufw delete allow 5353/udp; sudo ufw delete allow 7100/tcp; sudo ufw delete allow 7000/tcp; sudo ufw delete allow 7001/tcp; sudo ufw delete allow 7011/udp; sudo ufw delete allow 6001/udp; sudo ufw delete allow 6000/udp; sudo ufw delete allow proto udp to 224.0.0.251 port 5353'
